### ISSUE TITLE
Dumped soundbank asset list does not strip raw/ prefix and does not include file suffix for files

### ISSUE THREAD

**Issue by Laupetin** [Laupetin/OpenAssetTools#138]
Example:
Expected output: `sound\mus\zombie\tomb\egg\archangel.SN45.pc.snd.flac`
Actual output: `raw\sound\mus\zombie\tomb\egg\archangel.SN45.pc.snd`

**Comment by Jbleezy** [comment]
I think `raw\` prefix should stay since that is how it is in BO1.
