### ISSUE TITLE
Sound volumes are lower than expected

### ISSUE THREAD

**Issue by Jbleezy** [Laupetin/OpenAssetTools#155]
If you export a sound that is already in game using BO2 Sound Studio and use the same sound alias line that is given from Unlinker, the sound comes out lower than normal in game. This is especially noticeable with voicelines.

This could be an issue with exporting from BO2 Sound Studio, I'm not sure.

**Comment by Sammy-0** [comment]
The variables in unlinked aliases are a bit weird too, like volume and pitch have super high values for some reason. In particular the LFE alias for weapons seems exaggerated compared to the base game; maybe it was broken in the OG game or something?

**Comment by skiff** [comment]
@Jbleezy @Sammy-0 can you provide some examples? The fastfile and soundbank the original sound is in as well as an OAT built zone/soundbank that has this issue?

**Comment by Jbleezy** [comment]
I was adding the Richtofen Grief voicelines to Nuketown when I really noticed this issue.
Fastfile: `en_common_zm.ff`
Soundbank: `zmb_common.english`
[sound_volume_test.zip](https://github.com/Laupetin/OpenAssetTools/files/14952410/sound_volume_test.zip)

**Comment by Jbleezy** [comment]
In BO1 soundaliases, `vol_min` and `vol_max` go from 0 - 100, `pitch_min` goes from -100 - 0, and `pitch_max` goes from 0 - 100.

**Comment by Jbleezy** [comment]
Here is a video showcasing the issue and comparing it to what the volume should be:

https://vimeo.com/1009355363
