### ISSUE TITLE
Asset lowercase conversion does not work with IW5 leaderboard assets

### ISSUE THREAD

**Issue by Laupetin** [Laupetin/OpenAssetTools#180]
IW5's code_post_gfx_mp contains leaderboard assets that have an all uppercase name (like `DEFAULT_LB`).
This unfortunately means you currently cannot load them from in-memory since all attempts to load an asset with name `DEFAULT_LB` will result in OAT trying to find an asset with the name `default_lb`, which it cannot find.

The best solution here is probably to normalize asset names when adding them to the asset pool, since the game itself does compare and hash asset names case insensitive.

**Comment by Laupetin** [comment]
This should now be fixed with #188 being merged

**Comment by diamante0018** [comment]
I can confirm the issue was fixed.

**Comment by Laupetin** [comment]
Neat
