### ISSUE TITLE
[Linker]: Unable to extend patch_mp on latest and older versions

### ISSUE THREAD

**Issue by diamante0018** [Laupetin/OpenAssetTools#184]
Using  v0.12.1:
`.\bin\Unlinker.exe "D:\Steam\steamapps\common\Call of Duty Modern Warfare 3\zone\english\patch_mp.ff"`

copying over the dumped files to the correct location to proceed with re-linking (<OAT  Dir>/zone_raw).

`.\bin\Linker.exe -l "D:\Steam\steamapps\common\Call of Duty Modern Warfare 3\zone\english\patch_mp.ff" --menu-permissive --menu-no-optimization patch_mp`

Menu flags are required

The error list is HUGE

[oat.txt](https://github.com/Laupetin/OpenAssetTools/files/15219774/oat.txt)

I tried on a release version before the asset names were "lower cased" but it's the same issue, the Linker cannot find those xanims even with the asset names being half lowercase half uppercase.

**Comment by Laupetin** [comment]
This should now be fixed with #188 being merged

**Comment by diamante0018** [comment]
I honestly can't tell because it's either this fast file as genuinely some big issues or OAT can't find some assets in memory.

On a stock untouched raw dump of the fast file:
` -l "D:\Steam\steamapps\common\Call of Duty Modern Warfare 3\zone\english\patch_mp.ff" --menu-permissive --menu-no-optimization patch_mp`
[oat-log1.txt](https://github.com/Laupetin/OpenAssetTools/files/15285480/oat-log1.txt)

When actually extending the fast file with a mod
` -l "D:\Steam\steamapps\common\Call of Duty Modern Warfare 3\zone\english\patch_mp.ff" -l "mod.ff" --menu-permissive --menu-no-optimization patch_mp`

[oat-log2.txt](https://github.com/Laupetin/OpenAssetTools/files/15285495/oat-log2.txt)

**Comment by Laupetin** [comment]
> I honestly can't tell because it's either this fast file as genuinely some big issues or OAT can't find some assets in memory.
> 
> On a stock untouched raw dump of the fast file: ` -l "D:\Steam\steamapps\common\Call of Duty Modern Warfare 3\zone\english\patch_mp.ff" --menu-permissive --menu-no-optimization patch_mp` [oat-log1.txt](https://github.com/Laupetin/OpenAssetTools/files/15285480/oat-log1.txt)
> 
> When actually extending the fast file with a mod ` -l "D:\Steam\steamapps\common\Call of Duty Modern Warfare 3\zone\english\patch_mp.ff" -l "mod.ff" --menu-permissive --menu-no-optimization patch_mp`
> 
> [oat-log2.txt](https://github.com/Laupetin/OpenAssetTools/files/15285495/oat-log2.txt)

This is actually related to indirect asset references.
For example when a weapon references an anim, OAT will try to add it to the fastfile.
However the anim is only mentioned with a string, therefore it is not strictly dependent on it in terms of the asset references by pointer.
Due to this the original fastfile likely did not have these assets.

These errors would be suppressed if you for example dumped common_mp or whereever these anims are and ignored that zone file.

The logging of this is currently not very clear, that is true. The errors you have are not fatal errors though, the fastfile builds just as before.

**Comment by diamante0018** [comment]
Up to you to determine the progress on this issue tracker, I am not really that well versed on these assets stuff.

**Comment by Laupetin** [comment]
I'm closing this since the issue here is resolved and will open an issue to make the logging message more clear.
