### ISSUE TITLE
[Linker]: Recently added verbose logging line stopped working

### ISSUE THREAD

**Issue by diamante0018** [Laupetin/OpenAssetTools#302]
Version v0.19.1
Short description: `zone->m_name` is now apparently empty at https://github.com/Laupetin/OpenAssetTools/blob/main/src/ZoneWriting/ZoneWriting.cpp#L26

Full log https://git.alterware.dev/alterware/iw5-menus/actions/runs/103
```
Building zone "/workspace/alterware/iw5-menus/zone_out/localized_ui_mp/.ff"
Writing zone "" took 55302 ms.
Created zone "/workspace/alterware/iw5-menus/zone_out/localized_ui_mp/.ff"
Unloading search path: "/workspace/alterware/iw5-menus/zone_raw/localized_ui_mp"
```

**Comment by Laupetin** [comment]
Yup, it's the entire name of the zone, as you can see it writes a file with a very unhelpful name as well.
Fixed it and added some tests to make sure it and the rest is parsed as intended.
