### ISSUE TITLE
[Menu]: Add support for the pasting operator in the preprocessor

### ISSUE THREAD

**Issue by diamante0018** [Laupetin/OpenAssetTools#51]
It's needed to compile IW4 Menus, it's makes it almost impossible without

example: `name "cac_weapon_" ## weaponArg`

**Comment by Laupetin** [comment]
As i learned today
```cpp
#define GLUE(a, b) a ## b
GLUE("Hello", "World")
```
does not conform to C or C++ standard.

It does however work in MSVC, not in GCC or Clang however, making it a Microsoft extension.

Unfortunately Quake seemed to have implemented this in their preprocessor.
It is used in T5's modtools menu files as well.
So this needs to be implemented in OAT as well i am afraid

**Comment by Laupetin** [comment]
This makes it two preprocessor operators to implement:

## [Stringizing operator `#`](https://learn.microsoft.com/en-us/cpp/preprocessor/stringizing-operator-hash?view=msvc-170)

```cpp
#define STR(s) #s
STR(Hello) // -> "Hello"
```

## [Token pasting operator `##`](https://learn.microsoft.com/en-us/cpp/preprocessor/token-pasting-operator-hash-hash?view=msvc-170)

```cpp
#define GLUE(a, b) a ## b
GLUE(Hello, World) // -> HelloWorld

// This is a microsoft extension that the quake parser implemented as well
GLUE("Hello", "World") // -> "HelloWorld"
