### ISSUE TITLE
[Linker] Dual wield weapon anims not working correctly

### ISSUE THREAD

**Issue by Jbleezy** [Laupetin/OpenAssetTools#65]
I was trying to add Tac-45 Dual Wield to T6ZM but could not get the anims to work properly no matter what I tried.

Example project:
[zm_fnp45.zip](https://github.com/Laupetin/OpenAssetTools/files/13758853/zm_fnp45.zip)

**Comment by Laupetin** [comment]
I released a potential fix in version [0.6.0](https://github.com/Laupetin/OpenAssetTools/releases/tag/v0.6.0). Maybe you can check out whether this fixed it? I don't have a client that can parse uncompiled gsc and stuff.

**Comment by Jbleezy** [comment]
This has been fixed as of [0.7.1](https://github.com/Laupetin/OpenAssetTools/releases/tag/v0.7.1).
