### ISSUE TITLE
[Linker] The linker doesn't convert back slashes to forward slashes.

### ISSUE THREAD

**Issue by JezuzLizard** [Laupetin/OpenAssetTools#82]
Currently if you add an asset to your zone you can use back slashes in the name. While this works it is non standard and creates ambiguity on how to reference the asset. For example if you add a string table to your zone like this and you want to override the original mp/statstable.csv:

```
stringtable,mp\statstable.csv
```
instead of overriding the asset it will create a new asset which makes it unclear which one will actually be used since forward slashes and back slashes work the same way in paths but in cases where the name is directly compared it will be different.

**Comment by diamante0018** [comment]
perhaps make the linker halt and error out on incorrect syntax.
feels like only the "right" kind of slashes should be supported just like in canon GSC scripts.
if an error is undesirable a big warning should be displayed
