### ISSUE TITLE
[Linker: IW3]: Investigate localized string asset loading from raw

### ISSUE THREAD

**Issue by diamante0018** [Laupetin/OpenAssetTools#86]
Using the latest OAT on [this](https://cdn.discordapp.com/attachments/1076132145145319547/1197980343274319993/mod.ff) fastfile there is an issue with the localized assets.

The steps to reproduce should be the following:

1. Unlink the mod.ff
2. Take the zone_raw and try to relink it with the Linker.

If the issue is reproducible it should say it is unable to find localized asset for "mod".

**Comment by diamante0018** [comment]
I think this might be a new issue
![image](https://github.com/Laupetin/OpenAssetTools/assets/37080671/96846521-b4da-43de-9ceb-00752711a4a9)

**Comment by Laupetin** [comment]
IW3 just barely has any loaders currently. Only for Gfximage and rawfile currently it seems like. I just mainly used iw3 for dumping assets to compare them with iw4

**Comment by diamante0018** [comment]
If you wee to add the load code for the string tables as well from raw I think oat would become suitable to extend most mod.ff I found.
Thanks

**Comment by Laupetin** [comment]
> If you wee to add the load code for the string tables as well from raw I think oat would become suitable to extend most mod.ff I found. Thanks

Currently working on it

**Comment by Laupetin** [comment]
Should now be done with #90 and #91 -> Closing this
